social/app/urls.py
from django.urls import path
from .views import home_page, create_post, delete_post, edit_post, read_post
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',home_page,name='home'),
    path('post/create/',create_post,name='post-create'),
    path('post/delete/<pk>/',delete_post,name='post-delete'),
    path('post/edit/<pk>/',edit_post,name='post-edit'),
    path('post/read/<pk>/',read_post,name='post-read'),
    path('post/category/<tag>/',home_page,name='post-category'),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

social/appusers/urls.py
from django.urls import path
from .views import profile_page, edit_profile
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('profile/',profile_page, name='profile'),
    path('profile/edit',edit_profile, name='profile-edit'),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

social/social/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('', include('appusers.urls')),
    path('accounts/', include('allauth.urls')),
]

social/app/models.py
from django.db import models
import uuid
from autoslug import AutoSlugField

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=500)
    image = models.URLField(max_length=500)
    artist = models.CharField(max_length=500, null=True)
    url = models.URLField(max_length=500, null=True)
    body = models.TextField()
    tags = models.ManyToManyField('Tag')
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(max_length=100,default=uuid.uuid4,unique=True,primary_key=True,editable=False)
    
    def __str__(self):
        return str(self.title)
    
    class Meta:
        db_table = "posts"
        ordering = ['-created']

class Tag(models.Model):
    name = models.CharField(max_length=20)
    image = models.FileField(upload_to='icons/',null=True,blank=True)
    slug = AutoSlugField(populate_from='name',unique=True)
    
    def __str__(self):
        return str(self.name)
    

social/appusers/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='avatars/',null=True,blank=True)
    realname = models.CharField(max_length=50,null=True,blank=True)
    email = models.EmailField(unique=True,null=True)
    location = models.CharField(max_length=50,null=True,blank=True)
    bio = models.TextField(null=True,blank=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return str(self.user)
    

social/app/forms.py
from django.forms import ModelForm
from .models import Post
from django import forms

class PostCreateForm(ModelForm):
    class Meta:
        model = Post
        fields = ['url','body','tags']
        labels = {
            'body': 'Caption',
            'tags': 'Category'
        }
        widgets = {
            'body': forms.Textarea(attrs={'rows':3,'placeholder':'Caption your post...','class': 'font1 text-4xl'}),
            'url': forms.TextInput(attrs={'placeholder':'Paste url...'}),
            'tags': forms.CheckboxSelectMultiple(),
        }


class PostEditForm(ModelForm):
    class Meta:
        model = Post
        fields = ['body','tags']
        labels = {
            'body': '',
            'tags': 'Category'
        }
        widgets = {
            'body': forms.Textarea(attrs={'rows':3,'class': 'font1 text-4xl'}),
            'tags': forms.CheckboxSelectMultiple(),
        }

social/appusers/forms.py
from django.forms import ModelForm
from .models import Profile
from django import forms

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']
        labels = {
            'realname': 'Name'
        }
        widgets ={
            'image': forms.FileInput(),
            'bio': forms.Textarea(attrs={'rows':3})
        }

social/app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Tag
from .forms import PostCreateForm,PostEditForm
from bs4 import BeautifulSoup
import requests
from django.contrib import messages


# Create your views here.
def home_page(request,tag=None):
    if tag:
        posts = Post.objects.filter(tags__slug=tag)
        tag = get_object_or_404(Tag, slug=tag)
    else:
        posts = Post.objects.all()
        
    categories = Tag.objects.all()
        
    context = {'posts':posts, 'categories':categories,'tag':tag}
    return render(request,'app/home.html',context)

def create_post(request):
    form = PostCreateForm()
    
    if request.method == 'POST':
        form = PostCreateForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            
            web_url = requests.get(form.data['url'])
            soup = BeautifulSoup(web_url.text, 'html.parser')
            
            find_image = soup.select('meta[content^="https://live.staticflickr.com/"]')
            image = find_image[0]['content']
            post.image = image
            
            find_artist = soup.select('a.owner-name')
            artist = find_artist[0].text.strip()
            post.artist = artist
            
            find_title = soup.select('h1.photo-title')
            title = find_title[0].text.strip()
            post.title = title
            
            post.save()
            form.save_m2m()
            return redirect('home')
        
    context = {'form':form}
    return render(request, 'app/post_create.html', context)

def delete_post(request,pk):
    post = get_object_or_404(Post, id=pk)
    if request.method == 'POST':
        post.delete()
        messages.success(request,'Deleted successfully!')
        return redirect('home')
    context = {'post':post}
    return render(request, 'app/post_delete.html',context)

def edit_post(request,pk):
    post = get_object_or_404(Post, id=pk)
    form = PostEditForm(instance=post)
    
    if request.method == 'POST':
        form = PostEditForm(request.POST,instance=post)
        if form.is_valid():
            form.save()
            messages.success(request,'Updated successfully!')
            return redirect('home')
    context = {'post':post,'form':form}
    return render(request, 'app/post_edit.html', context)


def read_post(request, pk):
    post = get_object_or_404(Post, id=pk)
    context = {'post':post}
    return render(request, 'app/post_read.html', context)

social/appusers/views.py
from django.shortcuts import render, redirect
from .forms import ProfileForm

# Create your views here.
def profile_page(request):
    profile = request.user.profile
    context = {'profile':profile}
    return render(request,'appusers/profile.html',context)

def edit_profile(request):
    form = ProfileForm(instance=request.user.profile)
    if request.method == 'POST':
        form = ProfileForm(request.POST,request.FILES,instance=request.user.profile)
        if form.is_valid():
            form.save()
            return redirect('profile')
    context = {'form':form}
    return render(request,'appusers/profile_edit.html', context)

social/app/templates/includes/header.html
{% load static %}
<header x-data="{ mobilenavOpen: false }" class="md:flex items-center justify-between [&>*]:px-8 bg-gray-800 h-20 text-white sticky top-0 z-40">
    <div class="flex items-center justify-between h-20">
        <logo>
            <a class="flex items-center gap-1" href="/">
                <img class="w-6 mr-1 -mt-1" src="{% static 'images/fireheart_white.svg' %}"/>
                <span class="text-lg font-bold">Awesome</span>
            </a>
        </logo>
        <mobileicon class="md:hidden">
            <a @click="mobilenavOpen = !mobilenavOpen" class="h-12 w-12 flex items-center justify-center cursor-pointer hover:bg-gray-700 rounded-lg">
                <img x-show="!mobilenavOpen" class="w-6 h-6 select-none" src="https://img.icons8.com/small/64/ffffff/menu.png"/> 
                <img x-show="mobilenavOpen" x-cloak class="w-6 h-6 select-none" src="https://img.icons8.com/small/64/ffffff/delete-sign.png"/>
            </a>
        </mobileicon>
    </div>
    <nav x-show="mobilenavOpen" x-cloak class="md:!block bg-gray-800 h-screen w-screen md:h-auto md:w-auto -mt-20 md:mt-0 absolute md:relative z-[-1]"
    x-transition:enter="duration-300 ease-out"
    x-transition:enter-start="opacity-0 -translate-y-96"
    x-transition:enter-end="opacity-100 translate-y-0">
        <ul class="flex items-center navitems flex-col md:flex-row gap-8 md:gap-0 justify-center h-full -translate-y-10 md:translate-y-0">
            {% if user.is_authenticated %}
            <li><a href="/">Home</a></li>
            <li><a href="{% url 'post-create' %}">Create Post</a></li>
            <li x-data="{ dropdownOpen: false }" class="relative">
                <a @click="dropdownOpen = !dropdownOpen" @click.away="dropdownOpen = false" class="cursor-pointer select-none">
                    <img class="h-8 w-8 rounded-full object-cover" src="https://pbs.twimg.com/profile_images/508601156767997952/fFTdKUf2_400x400.jpeg"/>
                    {{user.username}}
                    <img x-bind:class="dropdownOpen && 'rotate-180 duration-300'" class="w-4" src="https://img.icons8.com/small/32/777777/expand-arrow.png"/>
                </a>
                <div x-show="dropdownOpen" x-cloak class="absolute right-0 bg-white text-black shadow rounded-lg w-40 p-2 z-20"
                x-transition:enter="duration-300 ease-out"
                x-transition:enter-start="opacity-0 -translate-y-5 scale-90"
                x-transition:enter-end="opacity-100 translate-y-0 scale-100">
                    <ul class="hoverlist [&>li>a]:justify-end">
                        <li><a href="">My Profile</a></li>
                        <li><a href="">Edit Profile</a></li>
                        <li><a href=" {% url 'account_logout' %}">Log Out</a></li>
                    </ul>
                </div>
            </li>
            {% else %}
            <li><a href="{% url 'account_login' %}">Login</a></li>
            <li><a href="{% url 'account_signup' %}">Signup</a></li>
            {% endif %}
        </ul>
    </nav>
</header>

social/templates/app/home.html
{% extends 'layouts/a.html' %}

{% block content%}
{% for post in posts %}

{% include 'includes/post.html' %}

{% endfor %}
{% endblock content %}

social/templates/app/post_create.html
{% extends 'layouts/b.html' %}

{% block content %}
<h1>Create Post</h1>
<div class="card !p-8">
    
    <div class="flex items-center mb-6">
        <img class="h-5 object-cover mr-1" src="https://img.icons8.com/small/96/333333/search--v1.png"/>
        <a href="https://www.flickr.com/explore" target="_blank" class="hover:underline text-gray-500">Find an image on Flickr</a>
    </div>

    <form method='POST'>
        {% csrf_token %}
        {{form.as_p}}
        
        <button type="submit" class="mt-1">Submit Post</button>
        <a class="button secondaryAction ml-1" href="{{ request.META.HTTP_REFERER }}">Cancel</a>
    </form>
</div>
{% endblock content %}

social/templates/app/post_delete.html
{% extends 'layouts/b.html' %}

{% block content %}
<div class="md:flex items-center">
    <div class="w-full md:max-w-sm mr-6 md:[&>*>*>p]:text-4xl">

        {% include 'includes/post.html' %}

    </div>
    <div>
        <h1>Delete Post</h1>
        <p class="mb-6">Are you sure you want to delete this post?</p>
        
        <form method='POST'>
            {% csrf_token %}
            <button type="submit">Confirm</button>
            <a class="button secondaryAction ml-1" href="{{ request.META.HTTP_REFERER }}">Go Back</a>
        </form>
    </div>
</div>
{% endblock content %}

social/templates/app/post_edit.html
{% extends 'layouts/b.html' %}

{% block content %}
<h1>Edit Post</h1>
<div class="card p-4">
    <div class="flex items-center mb-4">
        <img class="w-20 h-20 object-cover rounded-xl mr-4" src="https://live.staticflickr.com/65535/50618365686_36f887ab88_c.jpg">
        <h3 class="text-lg font-bold">{{post.title}}</h3>
    </div>
    
    <div class="pb-2">
        <form method='POST'>
            {% csrf_token %}
            {{form}}
            <div class="pt-4">
                <button type="submit">Submit</button>
                <a class="button secondaryAction ml-1" href="{{ request.META.HTTP_REFERER }}">Go Back</a>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

social/templates/app/post_read.html
{% extends 'layouts/a.html' %}

{% block content %}

{% include 'includes/post.html' %}

<div class="card !pb-0 -mt-3">
    <form method="POST" class="flex items-center p-4" autocomplete="off">
        <input type="text" name="comment" placeholder="Add comment ..." maxlength="150">
        <button @click="open = false" class="block ml-2" type="submit">Submit</button>
    </form>
</div>

<div class="mb-20">
    <div id="tabs" class="ml-4 flex gap-1 mb-4">
        <a class="tab selected">Newest First</a> 
        <a class="tab">Top Comments</a>
    </div>

    <div id="tab-contents">

        <comment class="card p-4 !mb-4">
            <div class="flex justify-between items-center"> 
                <a class="flex items-center gap-1 mb-2" href="">
                    <img class="w-8 h-8 object-cover rounded-full" src="https://img.icons8.com/small/96/A9A9A9/happy.png"> 
                    <span class="font-bold hover:underline">Bart</span>
                    <span class="text-sm font-normal text-gray-400">@bartsimpson</span>
                </a>
            </div>
            <p class="text-xl px-2">
                This is a comment from Bart
            </p>
            <div x-data="{ repliesOpen: false }" class="flex items-center justify-between flex-wrap text-sm px-2">
                <a @click="repliesOpen = !repliesOpen" class="font-bold hover:underline cursor-pointer">
                    <div class="inline-block" x-bind:class="repliesOpen && 'rotate-90 duration-300'">
                        <svg transform ="rotate(90)" width="9" height="9" viewBox="0 0 25 25">
                            <path d="M24 22h-24l12-20z"/>
                        </svg>
                    </div>
                    Replies
                    <span class="font-light text-gray-500 ml-1">1</span>
                </a>
                <div class="flex items-center gap-4 [&>a:hover]:underline">
                    <div class="flex items-center gap-1">
                        <img class="w-5 -mt-1" src="https://img.icons8.com/small/24/000000/fire-heart.png">
                        1
                    </div>
                    <a href="">Like</a>
                    <a href="">Delete</a>
                </div>

                <div x-show="repliesOpen" x-cloak class="basis-full mt-3 pl-8 grid grid-cols-1">

                    <reply class="flex items-end justify-between py-4 border-t">
                        <div class="flex">
                            <a href="">
                                <img class="w-8 h-8 object-cover rounded-full mr-2" src="https://img.icons8.com/small/96/A9A9A9/happy.png">
                            </a>
                            <div class="w-fit">
                                <a class="block" href="">
                                    <span class="font-bold hover:underline">Homer</span>
                                    <span class="text-sm text-gray-400">@homersimpson</span>
                                </a>
                                <div class="mr-3">This is a reply from Homer</div>
                            </div>
                        </div>
                        <div class="flex items-center gap-4 [&>a:hover]:underline">
                            <div class="flex items-center gap-1">
                                <img class="w-5 -mt-1" src="https://img.icons8.com/small/24/000000/fire-heart.png">
                                1
                            </div>
                            <a href="">Like</a>
                            <a href="">Delete</a>
                        </div>
                    </reply>

                    <form method="POST" class="replyform flex justify-between" autocomplete="off">
                        <input type="text" name="reply" placeholder="Add reply ..." maxlength="150">
                        <button class="block" type="submit">Submit</button>
                    </form>
                </div>
            </div> 
        </comment>

    </div>
</div>
{% endblock content %}

social/templates/appusers/profile.html
{% extends 'layouts/d.html' %}

{% block content %}
<div id="profile" class="flex flex-col items-center">
    
    <div class="w-full md:w-[36rem] lg:w-[50rem]">
        <div class="card p-6">
            <div class="text-center flex flex-col items-center">
                <img class="w-36 h-36 rounded-full object-cover mb-4" src="{{profile.image.url}}" />
                <div class="text-center max-w-md">
                    <h1>{{profile.realname}}</h1>
                    <div class="text-gray-400 mb-2 -mt-3">@{{profile.user.username}}</div>
                    <div class="flex items-center justify-center mx-auto">
                        <img class="object-cover h-6 mr-1 opacity-60" src="https://img.icons8.com/material-outlined/50/000000/marker.png"> 
                        {{profile.location}}
                    </div>
                    <div class="my-8">
                        {{profile.bio}}
                    </div> 
                    
                </div>
            </div>
        </div>
    </div>

    <div id="tabs" class="flex justify-center my-4 gap-2" > 
        <a class="tab selected">Latest</a>
        <a class="tab">Top Posts</a>  
        <a class="tab">Top Comments</a>
        <a class="tab">Liked Posts</a>
    </div>

    <div id="tab-contents" class="w-full flex flex-col items-center">
        
        <div class="grid place-items-start gap-x-8 max-w-xl mx-auto lg:grid-cols-2 lg:max-w-5xl xl:grid-cols-3 xl:max-w-7xl">

        <article class="card">
            <div class="flex items-center justify-between px-4 h-14">
                <h3 class="text-start leading-5 mr-1">Little Jedi</h3>
                <div class="text-sm text-gray-400 truncate">flickr<a href="" class="hover:underline ml-1" target="blank">@John Doe</a></div>
            </div>
            <figure>
                <a href=""><img class="w-full" src="https://live.staticflickr.com/65535/50618365686_36f887ab88_c.jpg"></a>
            </figure>
            <div class="p-4 pb-2">
                <a class="flex items-center gap-1 mb-4" href="">
                    <img class="w-8 h-8 object-cover rounded-full" src="https://img.icons8.com/small/96/A9A9A9/happy.png">
                    <span class="font-bold hover:underline">Lisa</span>
                    <span class="text-sm text-gray-400">@lisasimpson</span>
                </a>
                <p class="text-5xl mb-10 px-4 font1">Jedi Kitty protects the street</p>
                <div class="flex items-center gap-2 text-sm mb-5 flex-wrap">
                    <a class="bg-gray-200 rounded-full px-3 py-1 hover:bg-gray-800 hover:text-white" href="">Animals</a>
                    <a class="bg-gray-200 rounded-full px-3 py-1 hover:bg-gray-800 hover:text-white" href="">Black & White</a>
                </div>
                <div class="flex items-center justify-between text-sm px-2">
                    <a class="font-bold hover:underline" href="">Comments<span class="font-light text-gray-500 ml-2">3</span></a>
                    <div class="flex items-center gap-4 [&>a:hover]:underline">
                        <div class="flex items-center gap-1">
                            <img class="w-5 -mt-1" src="https://img.icons8.com/small/24/000000/fire-heart.png">1</div>
                        <a href="">Like</a>
                        <a href="">Edit</a>
                        <a href="">Delete</a>
                    </div>
                </div>
            </div>

        </article>

        <article class="card">
            <div class="flex items-center justify-between px-4 h-14">
                <h3 class="text-start leading-5 mr-1">Little Jedi</h3>
                <div class="text-sm text-gray-400 truncate">flickr<a href="" class="hover:underline ml-1" target="blank">@John Doe</a></div>
            </div>
            <figure>
                <a href=""><img class="w-full" src="https://live.staticflickr.com/65535/50618365686_36f887ab88_c.jpg"></a>
            </figure>
            <div class="p-4 pb-2">
                <a class="flex items-center gap-1 mb-4" href="">
                    <img class="w-8 h-8 object-cover rounded-full" src="https://img.icons8.com/small/96/A9A9A9/happy.png">
                    <span class="font-bold hover:underline">Lisa</span>
                    <span class="text-sm text-gray-400">@lisasimpson</span>
                </a>
                <p class="text-5xl mb-10 px-4 font1">Jedi Kitty protects the street</p>
                <div class="flex items-center gap-2 text-sm mb-5 flex-wrap">
                    <a class="bg-gray-200 rounded-full px-3 py-1 hover:bg-gray-800 hover:text-white" href="">Animals</a>
                    <a class="bg-gray-200 rounded-full px-3 py-1 hover:bg-gray-800 hover:text-white" href="">Black & White</a>
                </div>
                <div class="flex items-center justify-between text-sm px-2">
                    <a class="font-bold hover:underline" href="">Comments<span class="font-light text-gray-500 ml-2">3</span></a>
                    <div class="flex items-center gap-4 [&>a:hover]:underline">
                        <div class="flex items-center gap-1">
                            <img class="w-5 -mt-1" src="https://img.icons8.com/small/24/000000/fire-heart.png">1</div>
                        <a href="">Like</a>
                        <a href="">Edit</a>
                        <a href="">Delete</a>
                    </div>
                </div>
            </div>

        </article>

        <article class="card">
            <div class="flex items-center justify-between px-4 h-14">
                <h3 class="text-start leading-5 mr-1">Little Jedi</h3>
                <div class="text-sm text-gray-400 truncate">flickr<a href="" class="hover:underline ml-1" target="blank">@John Doe</a></div>
            </div>
            <figure>
                <a href=""><img class="w-full" src="https://live.staticflickr.com/65535/50618365686_36f887ab88_c.jpg"></a>
            </figure>
            <div class="p-4 pb-2">
                <a class="flex items-center gap-1 mb-4" href="">
                    <img class="w-8 h-8 object-cover rounded-full" src="https://img.icons8.com/small/96/A9A9A9/happy.png">
                    <span class="font-bold hover:underline">Lisa</span>
                    <span class="text-sm text-gray-400">@lisasimpson</span>
                </a>
                <p class="text-5xl mb-10 px-4 font1">Jedi Kitty protects the street</p>
                <div class="flex items-center gap-2 text-sm mb-5 flex-wrap">
                    <a class="bg-gray-200 rounded-full px-3 py-1 hover:bg-gray-800 hover:text-white" href="">Animals</a>
                    <a class="bg-gray-200 rounded-full px-3 py-1 hover:bg-gray-800 hover:text-white" href="">Black & White</a>
                </div>
                <div class="flex items-center justify-between text-sm px-2">
                    <a class="font-bold hover:underline" href="">Comments<span class="font-light text-gray-500 ml-2">3</span></a>
                    <div class="flex items-center gap-4 [&>a:hover]:underline">
                        <div class="flex items-center gap-1">
                            <img class="w-5 -mt-1" src="https://img.icons8.com/small/24/000000/fire-heart.png">1</div>
                        <a href="">Like</a>
                        <a href="">Edit</a>
                        <a href="">Delete</a>
                    </div>
                </div>
            </div>

        </article>

        </div>

    </div>

</div>
{% endblock content %}

social/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Awesome</title>
    <link rel="shortcut icon" type="image/png" href="https://img.icons8.com/small/64/000000/fire-heart.png"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js" defer></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <style type="text/tailwindcss">
        [x-cloak] { 
            display: none !important; 
        }
        :root {
            --primary: rgb(88, 40, 244);
            --primary-hover: rgb(69, 29, 200);
            --black: #1f2937;
            --font1: 'Lobster', sans-serif;
        }
        h1 {
            @apply text-4xl font-bold mb-4
        }
        h2 {
            @apply text-2xl font-bold mb-3
        }
        h3 {
            @apply text-lg font-bold 
        }
        .font1 {
            font-family: var(--font1);
        }
        .button, button, [type='submit'], [type='button'] {
            display: inline-flex;
            flex-wrap: wrap;
            align-items: center;
            justify-content: center;
            flex-shrink: 0;
            text-align: center;
            border-radius: 0.5rem;
            cursor: pointer;
            padding: 0 1rem;
            min-height: 3.3rem;
            font-weight: 600;
            box-shadow: 0 4px 3px rgba(0, 0, 0, 0.1);
            transition-property: transform;
            transition-duration: .2s;
            color: white;
            background-color: var(--primary);
            width: fit-content;
        }
        .button:hover, button:hover, [type='submit']:hover, [type='button']:hover {
            background-color: var(--primary-hover);
        }
        .button:active, button:active, [type='submit']:active, [type='button']:active {
            transform: scale(0.95);
        }
        .secondaryAction {
            background-color: white;
            color: rgba(0, 0, 0, 0.6);
            border: 1px solid rgba(0, 0, 0, 0.3);
        }
        .secondaryAction:hover, .button.secondaryAction:hover {
            background-color: rgba(0, 0, 0, 0.05);
        }
        .navitems>li>a {
            @apply flex items-center gap-2 h-12 px-4 hover:bg-gray-700 rounded-lg;
        }
        .card {
            display: flex;
            flex-direction: column;
            overflow: hidden;
            position: relative;
            border-radius: 1rem;
            box-shadow: 0 10px 15px -3px rgba(0,0,0,0.1);
            margin-bottom: 2rem;
            background-color: white;
            padding-bottom: 1rem;
            width: 100%;
        }
        .hoverlist>* {
            @apply hover:bg-gray-100 rounded-md transition duration-150;
        }
        .hoverlist>*>a {
            @apply flex items-center p-2;
        }
        .highlight {
            @apply !bg-indigo-100;
        }
        .titleBlip {
            animation: 1s fadeIn;
        }
        @keyframes fadeIn {
            0% { opacity: 0; }
            10% { opacity: 0; }
            100% { opacity: 1; }
        }
        html, body {
            margin: 0;
            min-height: 100%;
        }
        p {
            margin-bottom: 1rem;
        }
        form p {
            display: flex;
            align-items: center;
            margin-bottom: 1rem;
        }
        label, input {
          display: inline-block;
        }
        form p label {
            width: 7rem;
            }
        label {
            margin: 6px 0 3px;
        }
        input, textarea {
            width: 100%;
        }
        input[type="file"], select {
            background-color: white;
            padding-left: 0;
        }
        label[for="id_remember"] {
            width: auto;
            margin-right: 0.5rem;
        }
        input[name="remember"] {
            width: auto;
        }
        .btn-red {
            @apply inline-flex bg-red-500;
        }
        .btn-red:hover {
            @apply bg-red-600;
        }
        .login .secondaryAction {
            box-shadow: none;
            display: block;
            padding: none;
            padding: 0px;
            border: none;
            font-size: smaller;
            font-weight: normal;
            min-height: auto;
            margin-bottom: 1.5rem;
        }
        .login .secondaryAction:hover {
            @apply text-gray-500 underline bg-white;
        }
        #id_tags {
            margin-bottom: 1rem;
        }
        #id_tags div {
            display: inline-block;
            margin-right: 0.5rem;  
        }
        #id_tags div label {
            border-radius: 9999px;
            padding: 0.5rem 1rem;
            border: 1px solid rgb(229 231 235);
            width: auto;
            cursor: pointer;
            user-select: none;
        }
        #id_tags input {
            display: none;
        }
        #id_tags label:has(input:checked) {
            background-color: var(--black);
            color: white;
            border: 1px solid var(--black);
        }
        .textarea, textarea {
            margin-bottom: 1rem;
        }
        .textarea, textarea, input {
            border-radius: 0.5rem;
            padding: 1rem 1.2rem;
            background-color: rgba(232, 240, 254, 1);
        }
        .errorlist li {
            color: rgb(253, 88, 49);
            padding: 0.5rem;
            padding-left: 1rem;
            border-left: 5px solid rgb(253, 88, 49);
            margin-bottom: 1rem;
        }
        .tab {
            cursor: pointer;
            padding: 0.75rem 1rem;
            color: rgb(0,0,0,0.6); 
            background-color: rgb(0,0,0,0.05);
            border-radius: 0.75rem;
            text-align: center;
            display: flex;
            align-items: center;
        }
        .tab:hover {
            background-color: rgb(0,0,0,0.1);
        }
        .tab.selected {
            color: white;
            background-color: var(--black);
        }
        .replyform {
            border-top: none;
        }
        .replyform textarea, .replyform input {
            padding: 0.75rem 1rem;
            font-size: 1rem;
            margin-bottom: 0px;
            height: 3.2rem;
        }
        .replyform button {
            margin-left: 0.5rem;
            min-height: unset;
        }
        .fade-me-in.htmx-settling{
            opacity: 0;
        }
        .fade-me-in {
            opacity: 1;
            transition: opacity 1s ease-out;
        }
        #profile article figure img {
            @apply aspect-[3/2] object-cover;
        }
        #profile article p {
            @apply truncate leading-normal;
        }
    </style>
</head>
<body class="bg-gray-100">

{% include 'includes/messages.html' %}

{% include 'includes/header.html' %}

{% block layout %}
{% endblock layout %}
    
</body>
</html>